name: Azure Static Web Apps CI/CD

pr:
  branches:
    include:
      - main
trigger:
  branches:
    include:
      - main

jobs:
- job: build_and_deploy_job
  displayName: Build and Deploy Job
  condition: or(eq(variables['Build.Reason'], 'Manual'),or(eq(variables['Build.Reason'], 'PullRequest'),eq(variables['Build.Reason'], 'IndividualCI')))
  pool:
    vmImage: ubuntu-latest
  variables:
  - group: Azure-Static-Web-Apps-victorious-pebble-0501c0f0f-variable-group
  steps:
  - checkout: self
    submodules: true
  - task: Npm@1
    inputs:
      command: 'custom'
      workingDir: '.'
      customCommand: 'install -g @angular/cli@14.2.13'
    displayName: 'NPM - Install Angular CLI'
  - task: Npm@1
    inputs:
      command: 'ci'
      workingDir: '.'
    displayName: 'NPM - CI Install Packages'
  - task: Npm@1
    inputs:
      command: 'custom'
      workingDir: '.'
      customCommand: 'test'
    continueOnError: true
    displayName: 'NPM - Run unit tests'
  - task: PublishCodeCoverageResults@2
    inputs:
      summaryFileLocation: 'coverage/cobertura.xml'
      pathToSources: 'src'
      failIfCoverageEmpty: true
    displayName: 'Publish code coverage'
  - task: AzureStaticWebApp@0
    inputs:
      azure_static_web_apps_api_token: $(AZURE_STATIC_WEB_APPS_API_TOKEN_VICTORIOUS_PEBBLE_0501C0F0F)
      app_location: "/"
      api_location: ""
      output_location: "dist/angular-basic"